### PR TITLE
JWT Improvements

### PR DESCRIPTION
**Pull request by rafabene**
@lordofthejars Can you verify the following improvement that I've made?

It reduces some keycloak configuration steps by importing a pre-defined istio-realm.json file.

I've also improved the overall process to get and use the token and open keycloak console

### CODE REVIEW

**Comment by rafabene** [comment]
@lordofthejars Can you check it before modifying #154 ? It might help to rewrite the formular to get the valid token.

**Comment by lordofthejars** [comment]
@rafabene Yes, but in which sense it helps on the token you need to login as well, isn't it?

**Comment by rafabene** [comment]
@lordofthejars It just makes it easier to copy and paste.

**Comment by lordofthejars** [comment]
Yes copy paste the population of data, but not the generation of the token right? So RBAC section can be merged since we are only talking about the generation of the token.

**Comment by lordofthejars** [comment]
@rafabene I have reviewed but not executed and yes it is a really nice addition if you tried and feel that executing myself too is not necessary, merge it, no problem, it is really cool PR.

**Pull request merged**
