### PR TITLE
src: use bucharestgold base image for Node apps

### PR DESCRIPTION
**Pull request by lance**
Also adds linting and pino logger, and `npm start` instead of `node customer.js`.

### CODE REVIEW

**Comment by burrsutter** [comment]
I am trying to figure out why Node has to have its own Deployment.yml and not reuse the "base" that allows to all other langs/runtimes (in kubernetes/Deployment.yml)?

**Comment by burrsutter** [comment]
Also the "api/heath" endpoint would be unique to this implementation of customer/preference/recommendation thus making it "harder to learn" for anyone (like myself) who switches between the implementations.

**Comment by burrsutter** [comment]
It seems our Node implementation was "infected" by a Deployment.yml and Service.yml at some point in the past.  Those files should not be there but in the kubernetes directory

**Comment by lance** [comment]
> I am trying to figure out why Node has to have its own Deployment.yml and not reuse the "base" that allows to all other langs/runtimes (in kubernetes/Deployment.yml)?

There is no requirement that this be the case. The only difference are the liveness and readiness endpoints.

> Also the "api/heath" endpoint would be unique to this implementation of customer/preference/recommendation thus making it "harder to learn" for anyone (like myself) who switches between the implementations.

It's easy enough to change `kube-probe` to use any endpoint we want for either liveness or readiness - and they can be the same. But I'm curious why liveness and readiness in these examples are treated the same, since in reality they are not, and it seems like best practice would be to distinguish between the two. Would modifying the Java implementations to make that distinction be problematic?

> It seems our Node implementation was "infected" by a Deployment.yml and Service.yml at some point in the past. Those files should not be there but in the kubernetes directory

I was wondering about that myself. I'll use the common `.yaml` files once you help me with the answer re: liveness and readiness above.

**Comment by lance** [comment]
Closing this - out of date.

**Pull request closed without merging**
