### PR TITLE
feat(#104): Update to Istio 1.0.0

### PR DESCRIPTION
**Pull request by lordofthejars**

### CODE REVIEW

**Comment by rafabene** [comment]
After updating to 1.0 I was not able to make Prometheus work. It says "No datapoints found." for round(increase(istio_request_count{destination_service="recommendation.tutorial.svc.cluster.local" }[60m]))

**Comment by lordofthejars** [comment]
Hummm I checked grafana and I could make some requests and they were
reflected on graphs, but not directly in Prometheus

**Comment by lordofthejars** [comment]
Since Grafana was working I supposed that Prometheus was working correctly.
Wrong assumption sorry.

I'll take a look tomorrow, although I am not a super prometheus guy :D

**Comment by rafabene** [comment]
ACL rules are not working

**Pull request merged**
