### PR TITLE
update to Istio 1.0.2

### PR DESCRIPTION
**Pull request by rbaumgar**
update to the new Istio version.

### CODE REVIEW

**Comment by lordofthejars** [comment]
Thank you very much for this update, much appreciated, one small question have you tried some files to see that they work correctly? I have read some users complaining about some small problems in the migration from 1.0.0 to 1.0.1 so to be sure that we have not broken the demo too :)

Thank you so much again.

PS: Some day I will work on having automatic tests on it.

**Comment by rafabene** [comment]
Tested and merged....

**Comment by rafabene** [comment]
minishift 1.24, openshfit 3.10, and istio 1.0.2

**Comment by rafabene** [comment]
@lordofthejars Please, check the fix: https://github.com/redhat-developer-demos/istio-tutorial/commit/b402fe897dc84d00d8ed907618679acebc81dabc

**Comment by lordofthejars** [comment]
Thanks.

El dt., 2 d’oct. 2018 a les 22:10, Rafael Benevides (<
notifications@github.com>) va escriure:

**Pull request merged**
