### PR TITLE
Istio route using OpenTracing baggage

### PR DESCRIPTION
**Pull request by pavolloffay**
Signed-off-by: Pavol Loffay <ploffay@redhat.com>

### CODE REVIEW

**Comment by pavolloffay** [comment]
Merge should wait for https://github.com/jaegertracing/jaeger-client-java/pull/442

**Comment by rafabene** [comment]
@pavolloffay Can you check https://github.com/openshift-labs/learn-katacoda/blob/master/servicemesh/5-advanced-routerules/1useragent-routing.md and see if it needs to be updated also? Thank you

**Comment by pavolloffay** [comment]
The guide should work, however the explanation is not correct and it should mention that user-agent is added to baggage and the route uses baggage.

**Comment by pavolloffay** [comment]
@rafabene, as there are code changes the images needs to be rebuilt.

**Pull request merged**
