### PR TITLE
Dockerfile updates for vulnerabilities.

### PR DESCRIPTION
**Pull request by kameshsampath**
The docker file has been updated to fix the vulnerabilities shown by quay.io. The following issue has been raised https://github.com/fabric8io-images/java/issues/32 to fix base image

### CODE REVIEW

**Comment by lordofthejars** [comment]
One question `yum` operation is usually a long operation so is it strictly necessary for this demo? I am thinking for example in case of workshop where net is limited, downloading everything might be tedious so we either provide a container with everything already created (I know @kameshsampath  is working on that) or maybe we could just skip this `yum` update since it is just for demo purposes.

WDYT?

**Comment by kameshsampath** [comment]
@lordofthejars  the yum update is just for time being, i have raised a issue in fabric8 project to fix the same in base image.

**Comment by rafabene** [comment]
Hummm. I don't think this demo really requires the yum update. It will slow down the image build process and increase the network io.

**Comment by kameshsampath** [comment]
@rafabene  thats there temporarily until base fabric8 image is updated
as @burrsutter   wants the image w/o vulnerabilities

**Comment by rafabene** [comment]
Waiting new PR...

**Pull request closed without merging**
